@startuml db

entity songs {
    *id <unique>
    --
    *name
    *likes
    *listens
    lyrics
    *file_uri <unique>
    *author_id
}

entity songs_ganres {
    *song_id 
    *ganre_id
}

entity ganres {
    *id <unique>
    --
    *name <unique>
    description
}

entity authors{
    *id <unique>
    --
    * nickname
    first_name
    last_name
}

entity users{
    *id <unique>
    --
    *email <unique>
    first_name
    last_name
}

entity playlists{
    *id <unique>
    --
    *name
    *owner_id
    *is_public
}

entity playlists_songs{
    *playlist_id
    *song_id
}

entity playlists_users{
    *playlist_id
    *user_id
}

songs::id ||--|{ songs_ganres::song_id
songs_ganres::ganre_id }|--|| ganres::id
songs::author_id }|--|| authors::id
playlists::owner_id }|--|| users::id
playlists_songs::playlist_id }|--|| playlists::id
playlists_songs::song_id }|--|| songs::id
playlists_users::playlist_id }|--|| playlists::id
playlists_users::user_id }|--|| users::id


@enduml